services:
    php:
        build:
            dockerfile: ./.docker/php/Dockerfile
            context: .
            target: development
        volumes:
            - ./:/var/www/app
        ports:
            - "8800:80"
        env_file:
            -   .env
    db-events:
        image: postgres:18-alpine
        environment:
            POSTGRES_USER: cokido
            POSTGRES_PASSWORD: cokido
            POSTGRES_DB: events
        ports:
            - "5432:5432"
    db-projections:
        image: postgres:18-alpine
        environment:
            POSTGRES_USER: cokido
            POSTGRES_PASSWORD: cokido
            POSTGRES_DB: projections
        ports:
            - "5433:5432"
