# Welcome to Mago!
# For full documentation, see https://mago.carthage.software/tools/overview
version = "1"
php-version = "8.5.0"

[source]
workspace = "."
paths = ["bin", "public", "src"]
includes = ["packages", "vendor"]
excludes = ["vendor/nikic/fast-route/test/**", "vendor/brammm/smart/**", "packages/*/vendor/**"]

[source.glob]
literal-separator = true

[formatter]
preset = "default"
empty-line-after-property = true

[linter]
integrations = []

[linter.rules]
ambiguous-constant-access = { enabled = true }
ambiguous-function-call = { enabled = true }
excessive-parameter-list = { threshold = 8 }
no-alternative-syntax = { enabled = true }
no-fully-qualified-global-class-like = { enabled = true }
no-fully-qualified-global-constant = { enabled = true }
no-fully-qualified-global-function = { enabled = true }
string-style = { enabled = true, style = "concatenation" }

[analyzer]
plugins = []
find-unused-definitions = true
find-unused-expressions = true
analyze-dead-code = true
memoize-properties = true
strict-array-index-existence = true
check-throws = false
check-missing-override = true
find-unused-parameters = true
strict-list-index-checks = true
no-boolean-literal-comparison = true
check-missing-type-hints = true
register-super-globals = true
