version: '3'

silent: true

tasks:
    static-analysis:
        cmd: mago analyze
    lint:
        cmd: mago lint
    lint:fix:
        cmds: 
        - mago lint --fix --unsafe
        - mago format
