# Welcome to Mago!
# For full documentation, see https://mago.carthage.software/tools/overview
version = "1"
php-version = "8.5.0"

[source]
workspace = "."
paths = ["src/"]
includes = ["vendor"]
excludes = ["vendor/nikic/fast-route/test/**"]

[source.glob]
literal-separator = true

[formatter]
preset = "default"

[linter]
integrations = []

[linter.rules]
ambiguous-constant-access = { enabled = true }
ambiguous-function-call = { enabled = true }
no-alternative-syntax = { enabled = true }
no-fully-qualified-global-class-like = { enabled = true }
no-fully-qualified-global-constant = { enabled = true }
no-fully-qualified-global-function = { enabled = true }
string-style = { enabled = true, style = "concatenation" }
halstead = { effort-threshold = 7000 }

[analyzer]
plugins = ["psr-container"]
find-unused-definitions = true
find-unused-expressions = true
analyze-dead-code = true
memoize-properties = true
strict-array-index-existence = true
check-throws = true
check-missing-override = true
find-unused-parameters = true
strict-list-index-checks = true
no-boolean-literal-comparison = true
check-missing-type-hints = true
register-super-globals = true
